src/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from emails.views import (
    verify_email_token_view,
)
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("contact", views.contact, name="contact"),
    path("login/", views.login_logout_view, name="login"),
    path("logout/", views.login_logout_view, name="logout"),
    path("hx/", include("hx_endpoints.urls")),
    path(
        "verify/<uuid:token>", verify_email_token_view, name="verify_email_token_view"
    ),
    path("admin/", admin.site.urls),
    path("courses/", include("courses.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # for django-tailwind-browser reload
    urlpatterns += [path("__reload__/", include("django_browser_reload.urls"))]

src/hx_endpoints/urls.py
from django.urls import path, include
from .views import (
    email_token_login_view,
    logout_btn_hx_view,
    like_course_hx_view,
    like_lesson_hx_view,
    like_icon_hx_view,
    add_to_cart_hx_view,
    is_added_to_cart_hx_view,
    show_msg_toasts
)

app_name = "hx"
urlpatterns = [
    path("login/", email_token_login_view, name="login_form"),
    path("logout/", logout_btn_hx_view, name="logout_btn"),
    path("show-toasts/", show_msg_toasts, name="show_toasts"),
    path("like/c/<slug:course>", like_course_hx_view, name="like_course"),
    path("like/l/<slug:lesson>", like_lesson_hx_view, name="like_lesson"),
    path("add-to-cart/<course>", add_to_cart_hx_view, name="add_to_cart"),
    path(
        "is-added-to-cart/<course>", is_added_to_cart_hx_view, name="is_added_to_cart"
    ),
    path("like-icon/<instance>/<public_id>", like_icon_hx_view, name="get_like_icon"),
]

src/templates/base.html
{% load static %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>CPS | {%block title%} {%endblock title%}</title>
    <link
    rel="shortcut icon"
    href="{% static 'images/favicon.svg' %}"
    type="image/x-icon"
    />
    {% tailwind_css %}

    {% block extrahead %}
    {% endblock extrahead %}
    {% include "base/js.html" %}
  </head>
  <body hx-headers='{"X-CSRFToken":"{{csrf_token}}"}' class="font-sans dark:bg-gray-900">
      
    {% navbar request=request %}
    <div hx-get="{% url "hx:show_toasts" %}" hx-swap="outerHTML" hx-trigger="load"></div>
    <main x-data>
      {%block content%} 
      {%endblock content%}
    </main>
    
  </body>
</html>

src/templates/home.html
{% extends 'base.html'%} {%block title%} Home Page {%endblock title%} 

{%block content%}
<section class="bg-white dark:bg-gray-900">
  {% hero %}
</section>
{%endblock content%}