src/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from emails.views import (
    verify_email_token_view,
)
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("contact", views.contact, name="contact"),
    path("login/", views.login_logout_view, name="login"),
    path("logout/", views.login_logout_view, name="logout"),
    path("hx/", include("hx_endpoints.urls")),
    path(
        "verify/<uuid:token>", verify_email_token_view, name="verify_email_token_view"
    ),
    path("admin/", admin.site.urls),
    path("courses/", include("courses.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # for django-tailwind-browser reload
    urlpatterns += [path("__reload__/", include("django_browser_reload.urls"))]

src/courses/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.course_list_view, name="course_list_view"),
    path("<slug:course_id>/", views.course_detail_view, name="course_detail_view"),
    path(
        "<slug:course_id>/lessons/<slug:lesson_id>/",
        views.lesson_detail_view,
        name="lesson_detail_view",
    ),
]

src/hx_endpoints/urls.py
from django.urls import path, include
from .views import (
    email_token_login_view,
    logout_btn_hx_view,
    like_course_hx_view,
    like_lesson_hx_view,
    like_icon_hx_view,
    add_to_cart_hx_view,
    is_added_to_cart_hx_view,
    show_msg_toasts
)

app_name = "hx"
urlpatterns = [
    path("login/", email_token_login_view, name="login_form"),
    path("logout/", logout_btn_hx_view, name="logout_btn"),
    path("show-toasts/", show_msg_toasts, name="show_toasts"),
    path("like/c/<slug:course>", like_course_hx_view, name="like_course"),
    path("like/l/<slug:lesson>", like_lesson_hx_view, name="like_lesson"),
    path("add-to-cart/<course>", add_to_cart_hx_view, name="add_to_cart"),
    path(
        "is-added-to-cart/<course>", is_added_to_cart_hx_view, name="is_added_to_cart"
    ),
    path("like-icon/<instance>/<public_id>", like_icon_hx_view, name="get_like_icon"),
]

src/courses/models.py
import helpers
import uuid
from django.db import models
from django.utils.text import slugify
from cloudinary.models import CloudinaryField

helpers.cloudinary_init()


class PublishStatus(models.TextChoices):
    PUBLISHED = "pub", "Published"
    COMING_SOON = "soon", "Coming Soon"
    DRAFT = "draft", "Draft"


class AccessRequirement(models.TextChoices):
    ANYONE = "any", "Anyone"
    EMAIL_REQUIRED = "email_required", "Email Required"


def handle_upload(instance, filename):
    return f"{filename}"


def generate_public_id(instance, *args, **kwargs):
    title = instance.title
    unique_id = str(uuid.uuid4())
    if not title:
        return unique_id
    slug = slugify(title)
    unique_id_short = unique_id.replace("-", "")[:5]
    return f"{slug}-{unique_id_short}"


def get_public_id_prefix(instance, *args, **kwargs):
    if hasattr(instance, "path"):
        path = str(instance.path)
        if path.startswith("/"):
            path = path[1:]
        if path.endswith("/"):
            path = path[:-1]
        return path

    public_id = instance.public_id
    model_name = instance.__class__.__name__
    model_name_slug = slugify(model_name)
    if not public_id:
        return f"{model_name_slug}"
    return f"{model_name_slug}/{public_id}"


def get_display_name(instance, *args, **kwargs):
    title = instance.title
    if title:
        return str(title)
    model_name = instance.__class__.__name__
    return f"{model_name} Upload"


class Course(models.Model):
    title = models.CharField(max_length=200, blank=True)
    description = models.TextField(null=True, blank=True)
    public_id = models.CharField(max_length=210, blank=True, null=True, db_index=True)
    # price
    # discount
    # reviews
    thumbnail = CloudinaryField(
        "thumbnail",
        null=True,
        public_id_prefix=get_public_id_prefix,
        display_name=get_display_name,
        tags=["course", "thumbnail"],
    )
    access = models.CharField(
        max_length=20,
        choices=AccessRequirement.choices,
        default=AccessRequirement.EMAIL_REQUIRED,
    )
    status = models.CharField(
        max_length=15, choices=PublishStatus.choices, default=PublishStatus.DRAFT
    )
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if self.public_id is None:
            self.public_id = generate_public_id(self)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    @property
    def is_published(self):
        return self.status

    @property
    def avg_rating(self):
        reviews = self.reviews
        avg_rating = reviews.aggregate(models.Avg("rating")).get("rating__avg") or "0"
        return int(avg_rating)

    @property
    def reviews_count(self):
        return self.reviews.count()

    @property
    def admin_image_url(self):
        url = helpers.get_cloudinary_image_object(
            self, width=300, field_name="thumbnail"
        )
        return url

    @property
    def list_image_url(self):
        url = helpers.get_cloudinary_image_object(
            self, width=400, field_name="thumbnail"
        )
        return url

    @property
    def detail_image_url(self):
        url = helpers.get_cloudinary_image_object(
            self, width=750, field_name="thumbnail"
        )
        return url

    def get_absolute_url(self):
        return self.path

    @property
    def path(self):
        return f"/courses/{self.public_id}"

    def get_display_name(self):
        return f"{self.title} - Course"

    def get_image_thumbnail(self, width=500, as_html=False):
        return helpers.get_cloudinary_image_object(self, width=width, as_html=as_html)


class CourseReview(models.Model):
    email = models.ForeignKey("emails.email", on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="reviews")
    rating = models.IntegerField(choices=[(i, i) for i in range(1, 6)])
    review = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Review by {self.email}"

    class Meta:
        verbose_name = "Course Review"
        ordering = ["-created_at"]


class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    # course_id = when foreign key is added, related id field is also automatically added.
    public_id = models.CharField(max_length=210, blank=True, null=True)
    title = models.CharField(max_length=200, blank=True)
    description = models.TextField(null=True, blank=True)
    thumbnail = CloudinaryField(
        "image",
        blank=True,
        null=True,
        public_id_prefix=get_public_id_prefix,
        display_name=get_display_name,
        tags=["lesson", "thumbnail"],
    )
    video = CloudinaryField(
        "video",
        blank=True,
        null=True,
        type="private",
        resource_type="video",
        public_id_prefix=get_public_id_prefix,
        display_name=get_display_name,
        tags=["lesson", "video"],
    )
    order = models.IntegerField(default=0)
    can_preview = models.BooleanField(
        default=False, help_text="Can user without course access see this?"
    )
    status = models.CharField(
        max_length=15, choices=PublishStatus.choices, default=PublishStatus.PUBLISHED
    )
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["order", "-updated"]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.public_id is None:
            self.public_id = generate_public_id(self)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return self.path

    @property
    def path(self):
        course_path = self.course.path
        if course_path.endswith("/"):
            course_path = course_path[:-1]
        return f"{course_path}/lessons/{self.public_id}"

    def get_display_name(self):
        return f"{self.title} - {self.course.get_display_name}"

    @property
    def is_coming_soon(self):
        return self.status == PublishStatus.COMING_SOON

    @property
    def has_video(self):
        return self.video is not None

    @property
    def requires_email(self):
        return self.course.access == AccessRequirement.EMAIL_REQUIRED

    @property
    def admin_image_url(self):
        url = helpers.get_cloudinary_image_object(
            self, width=300, field_name="thumbnail"
        )
        return url

    @property
    def list_image_url(self):
        url = helpers.get_cloudinary_image_object(
            self, width=400, field_name="thumbnail"
        )
        return url

    @property
    def detail_image_url(self):
        url = helpers.get_cloudinary_image_object(
            self, width=750, field_name="thumbnail"
        )
        return url

    @property
    def avg_rating(self):
        reviews = self.reviews
        avg_rating = reviews.aggregate(models.Avg("rating")).get("rating__avg") or "0"
        return int(avg_rating)

    @property
    def reviews_count(self):
        return self.reviews.count()


class LessonReview(models.Model):
    email = models.ForeignKey("emails.email", on_delete=models.CASCADE)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, related_name="reviews")
    rating = models.IntegerField(choices=[(i, i) for i in range(1, 6)])
    review = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Review by {self.email}"

    class Meta:
        verbose_name = "Course Review"
        ordering = ["-created_at"]

src/courses/views.py
import helpers
from django.shortcuts import render
from django.http import Http404, HttpRequest,HttpResponse

from . import services


def course_list_view(request):
    """Show list of available published courses"""
    qs = services.get_published_courses()
    template_name = "courses/list.html"
    context = {
        "queryset": qs,
        "type": qs.first().__class__.__name__.lower(),
    }
    if request.htmx:
        template_name = "courses/components/course-cards.html"
        context["queryset"] = qs[:3]
        # return HttpResponse("Courses")
    return render(request, template_name, context)


def course_detail_view(request, course_id=None, *args, **kwargs):
    """Show the detailed view of individual course"""
    course_obj = services.get_course_detail(course_id=course_id)
    if course_obj is None:
        raise Http404
    lessons_qs = services.get_course_lessons(course_obj)
    return render(
        request,
        "courses/detail.html",
        {
            "object": course_obj,
            "queryset": lessons_qs,
            "type": lessons_qs.first().__class__.__name__.lower(),
        },
    )


def lesson_detail_view(
    request: HttpRequest, course_id=None, lesson_id=None, *args, **kwargs
):
    """
    Show the detailed view of specific published course.
    Use cloudinary embedded video player to play the video.
    """
    lesson_obj = services.get_lesson_detail(course_id=course_id, lesson_id=lesson_id)
    if lesson_obj is None or course_id is None:
        raise Http404

    # show email-required page for lesson(email-required) to visitors without email
    email_id_exists = request.session.get("email_id")
    if lesson_obj.requires_email and not email_id_exists:
        return render(request, "courses/email-required.html")

    # template_name = "courses/purchase-required.html"
    context = {"object": lesson_obj}
    template_name = "courses/lesson-coming-soon.html"
    if not lesson_obj.is_coming_soon and lesson_obj.has_video:
        # Lesson is already published and Video is available for the lesson
        template_name = "courses/lesson.html"
        video_embed_html = helpers.get_cloudinary_video_object(
            lesson_obj,
            field_name="video",
            width=600,
            as_html=True,
            autoplay=True,
            quality="auto:best",
        )
        context["video_embed"] = video_embed_html

    return render(request, template_name, context)

src/templates/courses/components/add-to-cart.html
<button
  type="button"
  hx-get="{% url 'hx:add_to_cart' course=item.public_id %}"
  hx-target="find span"
  hx-trigger="click delay:500ms"
  class="inline-flex items-center rounded-lg bg-primary-700 px-5 py-2.5 text-sm font-medium text-white hover:bg-primary-800 focus:outline-none focus:ring-4 focus:ring-primary-300 dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800"
>
  <svg
    class="-ms-2 me-2 h-5 w-5"
    aria-hidden="true"
    xmlns="http://www.w3.org/2000/svg"
    width="24"
    height="24"
    fill="none"
    viewBox="0 0 24 24"
  >
    <path
      stroke="currentColor"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="2"
      d="M4 4h1.5L8 16m0 0h8m-8 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4Zm8 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4Zm.75-3H7.5M11 7H6.312M17 4v6m-3-3h6"
    />
  </svg>
  <span hx-get="{% url 'hx:is_added_to_cart' course=item.public_id %}" hx-trigger="load" hx-target="this"></span>
</button>

src/templates/courses/components/course-card.html
{% load static %}
<div
  class="rounded-lg border border-gray-200 bg-white p-6 shadow-sm dark:border-gray-700 dark:bg-gray-800"
>
  <div class="h-56 w-full">
    <a href="{{item.get_absolute_url}}">
      <img
        class="mx-auto h-full rounded-lg object-contain"
        src="{% if item.admin_image_url  %}{{item.admin_image_url}}{% else %}{% static "images/fallback.svg" %}{% endif %}"
        alt=""
      />
    </a>
  </div>
  <div class="pt-6">
    <div class="mb-4 flex items-center justify-between gap-4">
      <span
        class="me-2 rounded bg-primary-100 px-2.5 py-0.5 text-xs font-medium text-primary-800 dark:bg-primary-900 dark:text-primary-300"
      >
        Up to 35% off
      </span>

      <div class="flex items-center justify-end gap-1">
        <button
          type="button"
          data-tooltip-target="tooltip-quick-look"
          class="rounded-lg p-2 text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white"
        >
          <span class="sr-only"> Quick look </span>
          <svg
            class="h-5 w-5"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            fill="none"
            viewBox="0 0 24 24"
          >
            <path
              stroke="currentColor"
              stroke-width="2"
              d="M21 12c0 1.2-4.03 6-9 6s-9-4.8-9-6c0-1.2 4.03-6 9-6s9 4.8 9 6Z"
            />
            <path
              stroke="currentColor"
              stroke-width="2"
              d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"
            />
          </svg>
        </button>
        <div
          id="tooltip-quick-look"
          role="tooltip"
          class="tooltip invisible absolute z-10 inline-block rounded-lg bg-gray-900 px-3 py-2 text-sm font-medium text-white opacity-0 shadow-sm transition-opacity duration-300 dark:bg-gray-700"
          data-popper-placement="top"
        >
          Quick look
          <div class="tooltip-arrow" data-popper-arrow=""></div>
        </div>

        {% include "courses/components/like-btn.html" %}
        <div
          id="tooltip-add-to-favorites"
          role="tooltip"
          class="tooltip invisible absolute z-10 inline-block rounded-lg bg-gray-900 px-3 py-2 text-sm font-medium text-white opacity-0 shadow-sm transition-opacity duration-300 dark:bg-gray-700"
          data-popper-placement="top"
        >
          Add to favorites
          <div class="tooltip-arrow" data-popper-arrow=""></div>
        </div>
      </div>
    </div>

    <a
      href="{{item.get_absolute_url}}"
      class="text-lg font-semibold leading-tight text-gray-900 hover:underline dark:text-white"
      >{{item.title}}</a
    >

    <div class="mt-2 flex items-center gap-2">
      <div class="flex items-center">
        {% with ''|center:item.avg_rating as stars %}
          {% for _ in stars %}
            {% include "courses/components/rating-star.html" %}
          {% endfor %}
        {% endwith %}
      </div>

      <p class="text-sm font-medium text-gray-900 dark:text-white">{{item.avg_rating}}</p>
      <p class="text-sm font-medium text-gray-500 dark:text-gray-400">({{item.reviews_count}})</p>
    </div>

    <ul class="mt-2 flex items-center gap-4">
      <li class="flex items-center gap-2">
        <svg 
        class="h-4 w-4 text-gray-500 dark:text-gray-100"
        fill="currentColor"
        viewBox="0 0 16 16" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
          <path d="M12.6 2.5c-1.6-1.2-1.6-2.5-1.6-2.5h-9v12.5c0 1.9 1.6 3.5 3.5 3.5h8.5v-13c0 0-1-0.2-1.4-0.5zM4 2h5v2h-5v-2zM13 15h-7.5c-1 0-1.8-0.6-2-1.3-0.1-0.4 0-0.7 0.4-0.7h7.1v-10.3c0.4 0.6 1.2 1.1 2 1.3v11z"></path>
          </svg>
        <p class="text-sm font-medium text-gray-500 dark:text-gray-400">
          Best Course
        </p>
      </li>

      <li class="flex items-center gap-2">
        <svg
          class="h-4 w-4 text-gray-500 dark:text-gray-400"
          aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
        >
          <path
            stroke="currentColor"
            stroke-linecap="round"
            stroke-width="2"
            d="M8 7V6c0-.6.4-1 1-1h11c.6 0 1 .4 1 1v7c0 .6-.4 1-1 1h-1M3 18v-7c0-.6.4-1 1-1h11c.6 0 1 .4 1 1v7c0 .6-.4 1-1 1H4a1 1 0 0 1-1-1Zm8-3.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0Z"
          />
        </svg>
        <p class="text-sm font-medium text-gray-500 dark:text-gray-400">
          Best Price
        </p>
      </li>
    </ul>

    {% if type == 'course' %}
      <div class="mt-4 flex items-center justify-between gap-4">
        <p
          class="text-2xl font-extrabold leading-tight text-gray-900 dark:text-white"
        >
          $1,699
        </p>
          {% include "courses/components/add-to-cart.html" %}
        </div>
      {% endif %}
  </div>
</div>

src/templates/courses/components/course-cards.html
<section class="bg-gray-50 py-3 antialiased dark:bg-gray-900 md:py-12">
    <div class="mx-auto max-w-screen-xl px-4 2xl:px-0">
      <!-- Heading & Filters -->
      <div
        class="mb-4 items-end justify-between space-y-4 sm:flex sm:space-y-0 md:mb-8"
      >
        <h2
          class="mt-3 text-xl font-semibold text-gray-900 dark:text-white sm:text-2xl"
        >
          Courses
        </h2>
      </div>
      <div
        class="mb-4 grid gap-4 sm:grid-cols-2 md:mb-8 lg:grid-cols-3 xl:grid-cols-4"
      >
        
        <!-- List of cards-->
         {% for item in queryset %}
          {% course_card item=item type=type%}
         {% endfor %}
        </div>
      </div>
    </div>
  </section>
  

src/templates/courses/components/like-btn.html
<button
type="button"
hx-get="{% if type == 'course' %} {% url 'hx:like_course' course=item.public_id %} {% else %} {% url 'hx:like_lesson' lesson=item.public_id %} {% endif %}"
hx-trigger="click delay:500ms"
data-tooltip-target="tooltip-add-to-favorites"
class="rounded-lg p-2 text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
        <span class="sr-only"> Add to Favorites </span>
        <span hx-trigger="load" hx-get="{% url 'hx:get_like_icon' instance=type public_id=item.public_id %}" hx-target="this" id="like-icon"></span>
</button>

src/templates/courses/components/rating-star.html
<svg
  class="h-4 w-4 text-yellow-400"
  aria-hidden="true"
  xmlns="http://www.w3.org/2000/svg"
  fill="currentColor"
  viewBox="0 0 24 24"
>
  <path
    d="M13.8 4.2a2 2 0 0 0-3.6 0L8.4 8.4l-4.6.3a2 2 0 0 0-1.1 3.5l3.5 3-1 4.4c-.5 1.7 1.4 3 2.9 2.1l3.9-2.3 3.9 2.3c1.5 1 3.4-.4 3-2.1l-1-4.4 3.4-3a2 2 0 0 0-1.1-3.5l-4.6-.3-1.8-4.2Z"
  />
</svg>