src/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from emails.views import (
    verify_email_token_view,
)
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("contact", views.contact, name="contact"),
    path("login/", views.login_logout_view, name="login"),
    path("logout/", views.login_logout_view, name="logout"),
    path("hx/", include("hx_endpoints.urls")),
    path(
        "verify/<uuid:token>", verify_email_token_view, name="verify_email_token_view"
    ),
    path("admin/", admin.site.urls),
    path("courses/", include("courses.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # for django-tailwind-browser reload
    urlpatterns += [path("__reload__/", include("django_browser_reload.urls"))]

src/courses/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.course_list_view, name="course_list_view"),
    path("<slug:course_id>/", views.course_detail_view, name="course_detail_view"),
    path(
        "<slug:course_id>/lessons/<slug:lesson_id>/",
        views.lesson_detail_view,
        name="lesson_detail_view",
    ),
]

src/hx_endpoints/urls.py
from django.urls import path, include
from .views import (
    email_token_login_view,
    logout_btn_hx_view,
    like_course_hx_view,
    like_lesson_hx_view,
    like_icon_hx_view,
    add_to_cart_hx_view,
    is_added_to_cart_hx_view,
    show_msg_toasts
)

app_name = "hx"
urlpatterns = [
    path("login/", email_token_login_view, name="login_form"),
    path("logout/", logout_btn_hx_view, name="logout_btn"),
    path("show-toasts/", show_msg_toasts, name="show_toasts"),
    path("like/c/<slug:course>", like_course_hx_view, name="like_course"),
    path("like/l/<slug:lesson>", like_lesson_hx_view, name="like_lesson"),
    path("add-to-cart/<course>", add_to_cart_hx_view, name="add_to_cart"),
    path(
        "is-added-to-cart/<course>", is_added_to_cart_hx_view, name="is_added_to_cart"
    ),
    path("like-icon/<instance>/<public_id>", like_icon_hx_view, name="get_like_icon"),
]

src/courses/models.py
import helpers
import uuid
from django.db import models
from django.utils.text import slugify
from cloudinary.models import CloudinaryField

helpers.cloudinary_init()


class PublishStatus(models.TextChoices):
    PUBLISHED = "pub", "Published"
    COMING_SOON = "soon", "Coming Soon"
    DRAFT = "draft", "Draft"


class AccessRequirement(models.TextChoices):
    ANYONE = "any", "Anyone"
    EMAIL_REQUIRED = "email_required", "Email Required"


def handle_upload(instance, filename):
    return f"{filename}"


def generate_public_id(instance, *args, **kwargs):
    title = instance.title
    unique_id = str(uuid.uuid4())
    if not title:
        return unique_id
    slug = slugify(title)
    unique_id_short = unique_id.replace("-", "")[:5]
    return f"{slug}-{unique_id_short}"


def get_public_id_prefix(instance, *args, **kwargs):
    if hasattr(instance, "path"):
        path = str(instance.path)
        if path.startswith("/"):
            path = path[1:]
        if path.endswith("/"):
            path = path[:-1]
        return path

    public_id = instance.public_id
    model_name = instance.__class__.__name__
    model_name_slug = slugify(model_name)
    if not public_id:
        return f"{model_name_slug}"
    return f"{model_name_slug}/{public_id}"


def get_display_name(instance, *args, **kwargs):
    title = instance.title
    if title:
        return str(title)
    model_name = instance.__class__.__name__
    return f"{model_name} Upload"


class Course(models.Model):
    title = models.CharField(max_length=200, blank=True)
    description = models.TextField(null=True, blank=True)
    public_id = models.CharField(max_length=210, blank=True, null=True, db_index=True)
    # price
    # discount
    # reviews
    thumbnail = CloudinaryField(
        "thumbnail",
        null=True,
        public_id_prefix=get_public_id_prefix,
        display_name=get_display_name,
        tags=["course", "thumbnail"],
    )
    access = models.CharField(
        max_length=20,
        choices=AccessRequirement.choices,
        default=AccessRequirement.EMAIL_REQUIRED,
    )
    status = models.CharField(
        max_length=15, choices=PublishStatus.choices, default=PublishStatus.DRAFT
    )
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if self.public_id is None:
            self.public_id = generate_public_id(self)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    @property
    def is_published(self):
        return self.status

    @property
    def avg_rating(self):
        reviews = self.reviews
        avg_rating = reviews.aggregate(models.Avg("rating")).get("rating__avg") or "0"
        return int(avg_rating)

    @property
    def reviews_count(self):
        return self.reviews.count()

    @property
    def admin_image_url(self):
        url = helpers.get_cloudinary_image_object(
            self, width=300, field_name="thumbnail"
        )
        return url

    @property
    def list_image_url(self):
        url = helpers.get_cloudinary_image_object(
            self, width=400, field_name="thumbnail"
        )
        return url

    @property
    def detail_image_url(self):
        url = helpers.get_cloudinary_image_object(
            self, width=750, field_name="thumbnail"
        )
        return url

    def get_absolute_url(self):
        return self.path

    @property
    def path(self):
        return f"/courses/{self.public_id}"

    def get_display_name(self):
        return f"{self.title} - Course"

    def get_image_thumbnail(self, width=500, as_html=False):
        return helpers.get_cloudinary_image_object(self, width=width, as_html=as_html)


class CourseReview(models.Model):
    email = models.ForeignKey("emails.email", on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="reviews")
    rating = models.IntegerField(choices=[(i, i) for i in range(1, 6)])
    review = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Review by {self.email}"

    class Meta:
        verbose_name = "Course Review"
        ordering = ["-created_at"]


class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    # course_id = when foreign key is added, related id field is also automatically added.
    public_id = models.CharField(max_length=210, blank=True, null=True)
    title = models.CharField(max_length=200, blank=True)
    description = models.TextField(null=True, blank=True)
    thumbnail = CloudinaryField(
        "image",
        blank=True,
        null=True,
        public_id_prefix=get_public_id_prefix,
        display_name=get_display_name,
        tags=["lesson", "thumbnail"],
    )
    video = CloudinaryField(
        "video",
        blank=True,
        null=True,
        type="private",
        resource_type="video",
        public_id_prefix=get_public_id_prefix,
        display_name=get_display_name,
        tags=["lesson", "video"],
    )
    order = models.IntegerField(default=0)
    can_preview = models.BooleanField(
        default=False, help_text="Can user without course access see this?"
    )
    status = models.CharField(
        max_length=15, choices=PublishStatus.choices, default=PublishStatus.PUBLISHED
    )
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["order", "-updated"]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.public_id is None:
            self.public_id = generate_public_id(self)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return self.path

    @property
    def path(self):
        course_path = self.course.path
        if course_path.endswith("/"):
            course_path = course_path[:-1]
        return f"{course_path}/lessons/{self.public_id}"

    def get_display_name(self):
        return f"{self.title} - {self.course.get_display_name}"

    @property
    def is_coming_soon(self):
        return self.status == PublishStatus.COMING_SOON

    @property
    def has_video(self):
        return self.video is not None

    @property
    def requires_email(self):
        return self.course.access == AccessRequirement.EMAIL_REQUIRED

    @property
    def admin_image_url(self):
        url = helpers.get_cloudinary_image_object(
            self, width=300, field_name="thumbnail"
        )
        return url

    @property
    def list_image_url(self):
        url = helpers.get_cloudinary_image_object(
            self, width=400, field_name="thumbnail"
        )
        return url

    @property
    def detail_image_url(self):
        url = helpers.get_cloudinary_image_object(
            self, width=750, field_name="thumbnail"
        )
        return url

    @property
    def avg_rating(self):
        reviews = self.reviews
        avg_rating = reviews.aggregate(models.Avg("rating")).get("rating__avg") or "0"
        return int(avg_rating)

    @property
    def reviews_count(self):
        return self.reviews.count()


class LessonReview(models.Model):
    email = models.ForeignKey("emails.email", on_delete=models.CASCADE)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, related_name="reviews")
    rating = models.IntegerField(choices=[(i, i) for i in range(1, 6)])
    review = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Review by {self.email}"

    class Meta:
        verbose_name = "Course Review"
        ordering = ["-created_at"]

src/courses/views.py
import helpers
from django.shortcuts import render
from django.http import Http404, HttpRequest,HttpResponse

from . import services


def course_list_view(request):
    """Show list of available published courses"""
    qs = services.get_published_courses()
    template_name = "courses/list.html"
    context = {
        "queryset": qs,
        "type": qs.first().__class__.__name__.lower(),
    }
    if request.htmx:
        template_name = "courses/components/course-cards.html"
        context["queryset"] = qs[:3]
        # return HttpResponse("Courses")
    return render(request, template_name, context)


def course_detail_view(request, course_id=None, *args, **kwargs):
    """Show the detailed view of individual course"""
    course_obj = services.get_course_detail(course_id=course_id)
    if course_obj is None:
        raise Http404
    lessons_qs = services.get_course_lessons(course_obj)
    return render(
        request,
        "courses/detail.html",
        {
            "object": course_obj,
            "queryset": lessons_qs,
            "type": lessons_qs.first().__class__.__name__.lower(),
        },
    )


def lesson_detail_view(
    request: HttpRequest, course_id=None, lesson_id=None, *args, **kwargs
):
    """
    Show the detailed view of specific published course.
    Use cloudinary embedded video player to play the video.
    """
    lesson_obj = services.get_lesson_detail(course_id=course_id, lesson_id=lesson_id)
    if lesson_obj is None or course_id is None:
        raise Http404

    # show email-required page for lesson(email-required) to visitors without email
    email_id_exists = request.session.get("email_id")
    if lesson_obj.requires_email and not email_id_exists:
        return render(request, "courses/email-required.html")

    # template_name = "courses/purchase-required.html"
    context = {"object": lesson_obj}
    template_name = "courses/lesson-coming-soon.html"
    if not lesson_obj.is_coming_soon and lesson_obj.has_video:
        # Lesson is already published and Video is available for the lesson
        template_name = "courses/lesson.html"
        video_embed_html = helpers.get_cloudinary_video_object(
            lesson_obj,
            field_name="video",
            width=600,
            as_html=True,
            autoplay=True,
            quality="auto:best",
        )
        context["video_embed"] = video_embed_html

    return render(request, template_name, context)

src/templates/courses/detail.html
{% extends 'base.html'%} 
{%block title%} Courses Detail {%endblock title%}
{%block content%}
<section class="bg-gray-50 py-3 antialiased dark:bg-gray-900 md:py-12">
  <div class="mx-auto max-w-screen-xl px-4 2xl:px-0">
    <!-- Heading & Filters -->
    <div
      class="mb-4 items-end justify-between space-y-4 sm:flex sm:space-y-0 md:mb-8"
    >
      <h2
        class="mt-3 text-xl font-semibold text-gray-900 dark:text-white sm:text-2xl"
      >
        Lessons
      </h2>
    </div>
    <div class="font-semibold mb-5  dark:text-white">
      <h2 class="text-lg text-gray-900 sm:text-xl">Description</h2>
      <p class="text-center text-sm">{{object.description}}</p>
      <p class="text-center text-sm">Rating: {{object.avg_rating}}</p>
      <p class="text-center text-sm">No of reviews: {{object.reviews_count}}</p>
    </div>
    <div
      class="mb-4 grid gap-4 sm:grid-cols-2 md:mb-8 lg:grid-cols-3 xl:grid-cols-4"
    >
      {% for item in queryset %}
        {% course_card item=item type=type%}
      {% endfor %}
    </div>
  </div>
</section>

{%endblock content%}

src/templates/courses/email-required.html
{% extends 'base.html'%}
{% load static %}

{%block title%}
    Unlock content
{%endblock title%}


{%block content%}
<section class="bg-gray-50 dark:bg-gray-900">
    <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
        <a href="#" class="flex items-center mb-6 text-2xl font-semibold text-gray-900 dark:text-white">
            <img class="w-8 h-8 mr-2" src="{% static "images/favicon.svg" %}" alt="logo">
            Verify to unlock course
        </a>
        <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
            <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
            <div hx-get="{% url 'hx:login_form' %}" hx-trigger="load">
                
            </div>
        </div>
    </div>
  </section>

{%endblock content%}

src/templates/courses/lesson-coming-soon.html
{% extends 'base.html'%}
{% load static %}
{%block title%} Lesson Coming Soon {%endblock title%}

{%block content%}
<section class="bg-white py-8 antialiased dark:bg-gray-900 md:py-16">
  <div class="mx-auto max-w-screen-xl px-1 2xl:px-0">
    <div class="mx-auto max-w-5xl">
      <!-- lesson title -->
      <h2
        class="text-xl font-semibold text-gray-900 dark:text-white sm:text-2xl"
      >
        {{lesson_obj.title}}
      </h2>

      <!-- lesson description -->
      <div class="max-w-2xl mx-auto space-y-6 my-4">
          <h2 class="text-md font-semibold text-gray-900 dark:text-white sm:text-lg" >New Lesson Coming Soon!</h2>
        <p class="ont-medium text-gray-700 dark:text-gray-400 text-justify">
            Get ready for exciting new lessons on your learning journey! We’re preparing fresh content designed to help you expand your skills and knowledge. Stay tuned for updates – more to come!
        </p>
      </div>

      <!-- Lesson Image -->
      <div class="my-8 overflow-hidden">
        <img class="dark:block mx-auto object-contain h-96 rounded-3xl" src="{% static "images/coming-soon.gif" %}" alt="Coming soon gif" />
      </div>
    </div>
  </div>
</section>

{%endblock content%}

src/templates/courses/lesson.html
{% extends 'base.html'%}
{% load static %}
<!-- Add cloudinary css and js for video player -->
{% block extrahead %}
{% include 'base/cld-js.html'%}
{% endblock extrahead %}

{%block title%}
Lesson Detail
{%endblock title%}

{%block content%}
<section class="bg-white py-8 antialiased dark:bg-gray-900 md:py-16">
    <div class="mx-auto max-w-screen-xl px-1 2xl:px-0">
      <div class="mx-auto max-w-5xl">
        <!-- lesson title -->
        <h2
          class="text-xl font-semibold text-gray-900 dark:text-white sm:text-2xl"
        >
          {{object.title}} 

        </h2>

        <!-- lesson description -->
        <div class="max-w-2xl space-y-6 my-4">
            <h2 class="text-lg font-semibold text-gray-900 dark:text-white sm:text-xl" >Description</h2>
            <p class="text-base font-medium text-gray-700 dark:text-gray-400">
              {{object.description}}
            </p>
          </div>
  
        <!-- Lesson Image -->
        <div class="my-8 overflow-hidden ">
          <img
            class="dark:block mx-auto object-contain h-96 rounded-3xl"
            src="{% if object.detail_image_url  %}{{object.list_image_url}}{% else %}{% static "images/fallback.svg" %}{% endif %}"
            alt=""
          />
        </div>
  
        
        <!-- lesson video -->
        <div class="my-6 md:my-12 rounded-lg flex items-center justify-center">
            {{video_embed}}
        </div>
      </div>
    </div>
  </section>
  


{%endblock content%}

src/templates/courses/list.html
{% extends 'base.html'%}

{%block title%}
Courses List
{%endblock title%}


{%block content%}
{% include "courses/components/course-cards.html" %}
{%endblock content%}